[package]
name = "api-mysql"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "1.0.0", features = ["mysql"]}
diesel_codegen = { version = "0.16.0", features = ["mysql"] }
dotenv = "0.9.0"
rprompt = "1.0"